# Generated by Django 6.1.1 on 2026-09-28 23:06

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permiso',
            name='modulo',
            field=models.CharField(choices=[('usuarios_seguridad', 'Usuarios y Seguridad'), ('productos_inventario', 'Productos e Inventario'), ('compras', 'Compras y Proveedores'), ('comercializacion', 'Comercialización'), ('reportes', 'Reportes')], default='usuarios_seguridad', max_length=30, verbose_name='Módulo o Paquete'),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='nombre',
            field=models.CharField(help_text='Identificador único del permiso en código (ej. asignar_permisos).', max_length=50, unique=True, verbose_name='Nombre del Permiso'),
        ),
        migrations.AddConstraint(
            model_name='permiso',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='permiso_nombre_unico_ci', violation_error_message='Ya existe un permiso con este nombre (no distingue mayúsculas).'),
        ),
    ]
