# Generated by Django 6.1.1 on 2026-09-27 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=50, unique=True, verbose_name='Nombre de usuario')),
                ('password', models.CharField(db_column='hash_contrasena', max_length=255, verbose_name='Hash de contraseña')),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Correo electrónico')),
                ('activo', models.BooleanField(default=True, verbose_name='Usuario activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Acceso al panel admin')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Es superadministrador')),
                ('groups', models.ManyToManyField(blank=True, related_name='panaderia_usuarios', to='auth.group', verbose_name='Grupos')),
                ('id_rol', models.ForeignKey(blank=True, db_column='id_rol', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='roles.rol', verbose_name='Rol asignado')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='panaderia_usuarios_permissions', to='auth.permission', verbose_name='Permisos de Django')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
                'ordering': ['id_usuario'],
            },
        ),
    ]
