# Generated by Django 6.1.1 on 2026-09-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='bloqueado_hasta',
            field=models.DateTimeField(blank=True, help_text='Instante en que expira el bloqueo. Null significa cuenta desbloqueada.', null=True, verbose_name='Bloqueado hasta'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='intentos_fallidos',
            field=models.PositiveSmallIntegerField(default=0, help_text='Se reinicia a 0 tras un inicio de sesión exitoso.', verbose_name='Intentos fallidos consecutivos'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultimo_intento_fallido',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último intento fallido'),
        ),
    ]
