# Generated by Django 6.1.1 on 2026-09-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usuario_bloqueado_hasta_usuario_intentos_fallidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='intentos_fallidos',
            field=models.PositiveSmallIntegerField(db_default=0, default=0, help_text='Se reinicia a 0 tras un inicio de sesión exitoso.', verbose_name='Intentos fallidos consecutivos'),
        ),
    ]
