# Generated by Django 6.1.1 on 2026-09-28 23:06

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0002_permiso_modulo_alter_permiso_nombre_and_more'),
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rolpermiso',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='rol',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='rol_nombre_unico_ci', violation_error_message='Ya existe un rol con este nombre (no distingue mayúsculas).'),
        ),
        migrations.AddConstraint(
            model_name='rolpermiso',
            constraint=models.UniqueConstraint(fields=('rol', 'permiso'), name='rol_permiso_unico', violation_error_message='Este rol ya tiene asignado dicho permiso.'),
        ),
    ]
