# Generated by Django 6.1.1 on 2026-09-27 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='nombre_usuario_intento',
            field=models.CharField(blank=True, help_text='Nombre de usuario digitado en un intento de acceso fallido.', max_length=50, null=True, verbose_name='Usuario intentado'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', help_text='Null cuando el evento no proviene de un usuario autenticado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras', to=settings.AUTH_USER_MODEL, verbose_name='Usuario responsable'),
        ),
    ]
