# Generated by Django 6.1.1 on 2026-09-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0002_bitacora_nombre_usuario_intento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='agente_usuario',
            field=models.CharField(blank=True, help_text='User-Agent del cliente. Ayuda a distinguir un ataque automatizado de un humano.', max_length=255, null=True, verbose_name='Agente de usuario (navegador)'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='accion',
            field=models.CharField(choices=[('INICIO_SESION', 'Inicio de sesión'), ('LOGIN_FALLIDO', 'Intento de acceso fallido'), ('ACCESO_BLOQUEADO', 'Acceso rechazado por bloqueo'), ('ACCESO_DENEGADO', 'Acceso denegado por cuenta inactiva'), ('CIERRE_SESION', 'Cierre de sesión'), ('DESBLOQUEO_CUENTA', 'Desbloqueo manual de cuenta')], max_length=50, verbose_name='Acción realizada'),
        ),
    ]
