# Generated by Django 6.1.1 on 2026-09-27 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0004_sincronizar_fk_bitacora_set_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='accion',
            field=models.CharField(choices=[('INICIO_SESION', 'Inicio de sesión'), ('LOGIN_FALLIDO', 'Intento de acceso fallido'), ('ACCESO_BLOQUEADO', 'Acceso rechazado por bloqueo'), ('ACCESO_DENEGADO', 'Acceso denegado por cuenta inactiva'), ('CIERRE_SESION', 'Cierre de sesión'), ('DESBLOQUEO_CUENTA', 'Desbloqueo manual de cuenta'), ('SOLICITUD_RECUPERACION', 'Solicitud de recuperación de contraseña'), ('RECUPERACION_CONFIRMADA', 'Contraseña restablecida por recuperación'), ('RECUPERACION_INVALIDADA', 'Enlace de recuperación rechazado')], max_length=50, verbose_name='Acción realizada'),
        ),
    ]
