# Generated by Django 6.1.1 on 2026-09-29 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0006_alter_bitacora_accion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='accion',
            field=models.CharField(choices=[('INICIO_SESION', 'Inicio de sesión'), ('LOGIN_FALLIDO', 'Intento de acceso fallido'), ('ACCESO_BLOQUEADO', 'Acceso rechazado por bloqueo'), ('ACCESO_DENEGADO', 'Acceso denegado por cuenta inactiva'), ('CIERRE_SESION', 'Cierre de sesión'), ('DESBLOQUEO_CUENTA', 'Desbloqueo manual de cuenta'), ('SOLICITUD_RECUPERACION', 'Solicitud de recuperación de contraseña'), ('RECUPERACION_CONFIRMADA', 'Contraseña restablecida por recuperación'), ('RECUPERACION_INVALIDADA', 'Enlace de recuperación rechazado'), ('ALTA_USUARIO', 'Alta de usuario'), ('EDICION_USUARIO', 'Modificación de usuario'), ('CAMBIAR_ESTADO_USUARIO', 'Activación o inactivación de usuario'), ('RESTABLECER_CONTRASENA', 'Restablecimiento administrativo de contraseña'), ('ALTA_ROL', 'Alta de rol'), ('EDICION_ROL', 'Modificación de rol'), ('ASIGNAR_PERMISO_ROL', 'Asignación de permiso a rol'), ('REVOCAR_PERMISO_ROL', 'Revocación de permiso de rol'), ('ACTUALIZACION_MATRIZ_PERMISOS', 'Reemplazo masivo de matriz de permisos')], max_length=50, verbose_name='Acción realizada'),
        ),
    ]
