# Generated by Django 5.1.1 on 2026-09-29 01:19

from django.db import migrations, models

# Antes de este cambio CU5 escribía estas acciones como texto suelto, fuera del
# vocabulario AccionBitacora; sin renombrarlas quedarían separadas de las nuevas
# en cualquier filtro de CU26.
ACCIONES_PRODUCTO = {
    'CREACION': 'ALTA_PRODUCTO',
    'MODIFICACION': 'EDICION_PRODUCTO',
    'CAMBIO_ESTADO': 'CAMBIAR_ESTADO_PRODUCTO',
}


def renombrar_acciones_producto(apps, schema_editor):
    Bitacora = apps.get_model('bitacora', 'Bitacora')
    for anterior, nueva in ACCIONES_PRODUCTO.items():
        Bitacora.objects.filter(tabla_afectada='producto', accion=anterior).update(accion=nueva)


def restaurar_acciones_producto(apps, schema_editor):
    Bitacora = apps.get_model('bitacora', 'Bitacora')
    for anterior, nueva in ACCIONES_PRODUCTO.items():
        Bitacora.objects.filter(tabla_afectada='producto', accion=nueva).update(accion=anterior)


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0007_alter_bitacora_accion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='accion',
            field=models.CharField(choices=[('INICIO_SESION', 'Inicio de sesión'), ('LOGIN_FALLIDO', 'Intento de acceso fallido'), ('ACCESO_BLOQUEADO', 'Acceso rechazado por bloqueo'), ('ACCESO_DENEGADO', 'Acceso denegado por cuenta inactiva'), ('CIERRE_SESION', 'Cierre de sesión'), ('DESBLOQUEO_CUENTA', 'Desbloqueo manual de cuenta'), ('SOLICITUD_RECUPERACION', 'Solicitud de recuperación de contraseña'), ('RECUPERACION_CONFIRMADA', 'Contraseña restablecida por recuperación'), ('RECUPERACION_INVALIDADA', 'Enlace de recuperación rechazado'), ('ALTA_USUARIO', 'Alta de usuario'), ('EDICION_USUARIO', 'Modificación de usuario'), ('CAMBIAR_ESTADO_USUARIO', 'Activación o inactivación de usuario'), ('RESTABLECER_CONTRASENA', 'Restablecimiento administrativo de contraseña'), ('ALTA_ROL', 'Alta de rol'), ('EDICION_ROL', 'Modificación de rol'), ('ASIGNAR_PERMISO_ROL', 'Asignación de permiso a rol'), ('REVOCAR_PERMISO_ROL', 'Revocación de permiso de rol'), ('ACTUALIZACION_MATRIZ_PERMISOS', 'Reemplazo masivo de matriz de permisos'), ('ALTA_PRODUCTO', 'Alta de producto'), ('EDICION_PRODUCTO', 'Modificación de producto'), ('CAMBIAR_ESTADO_PRODUCTO', 'Activación o inactivación de producto'), ('ALTA_PROVEEDOR', 'Alta de proveedor'), ('EDICION_PROVEEDOR', 'Modificación de proveedor'), ('CAMBIAR_ESTADO_PROVEEDOR', 'Activación o inactivación de proveedor')], max_length=50, verbose_name='Acción realizada'),
        ),
        migrations.RunPython(renombrar_acciones_producto, restaurar_acciones_producto),
    ]
