# Generated by Django 6.1.1 on 2026-09-27 23:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenRecuperacion',
            fields=[
                ('id_token', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID del token')),
                ('token_hash', models.CharField(help_text='SHA-256 del token. El token en claro nunca se almacena.', max_length=64, unique=True, verbose_name='Hash del token')),
                ('email_destino', models.EmailField(help_text='Correo al que se envió el enlace en el momento de la solicitud.', max_length=150, verbose_name='Correo de destino')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado en')),
                ('expira_en', models.DateTimeField(verbose_name='Expira en')),
                ('usado_en', models.DateTimeField(blank=True, help_text='Instante en que se confirmó una contraseña con este token. NULL = sin usar.', null=True, verbose_name='Usado en')),
                ('invalidado_en', models.DateTimeField(blank=True, help_text='Instante en que se canceló: por pedir otro token o por agotar los intentos.', null=True, verbose_name='Invalidado en')),
                ('intentos', models.PositiveSmallIntegerField(default=0, help_text='Confirmaciones fallidas con este token. Al superar el máximo se invalida.', verbose_name='Intentos de confirmación')),
                ('ip_origen', models.CharField(blank=True, help_text='Máx. 45 = longitud máxima de una IPv6.', max_length=45, null=True, verbose_name='IP de origen')),
                ('agente_usuario', models.CharField(blank=True, max_length=255, null=True, verbose_name='Agente de usuario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_recuperacion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Token de Recuperación',
                'verbose_name_plural': 'Tokens de Recuperación',
                'db_table': 'token_recuperacion',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['usuario', '-creado_en'], name='token_recuperacion_usuario_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('expira_en__gt', models.F('creado_en'))), name='token_recuperacion_expiracion_positiva'), models.CheckConstraint(condition=models.Q(('intentos__gte', 0)), name='token_recuperacion_intentos_no_negativos'), models.CheckConstraint(condition=models.Q(('usado_en__isnull', True), ('usado_en__gte', models.F('creado_en')), _connector='OR'), name='token_recuperacion_uso_coherente')],
            },
        ),
    ]
