# Generated by Django 5.1.1 on 2026-09-28 06:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id_categoria', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la categoría')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría de producto',
                'verbose_name_plural': 'Categorías de producto',
                'db_table': 'categoria_producto',
                'ordering': ['id_categoria'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del producto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('costo_produccion', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo de producción (Bs)')),
                ('porcentaje_ganancia', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Porcentaje de ganancia')),
                ('precio_sugerido', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio sugerido (Bs)')),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio de venta (Bs)')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro')),
                ('activo', models.BooleanField(default=True, verbose_name='Producto activo')),
                ('id_categoria', models.ForeignKey(blank=True, db_column='id_categoria', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='productos_inventario.categoriaproducto', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'ordering': ['id_producto'],
            },
        ),
        migrations.CreateModel(
            name='HistorialPrecioProducto',
            fields=[
                ('id_historial', models.BigAutoField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio (Bs)')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Vigente desde')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, related_name='historial_precios', to='productos_inventario.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Historial de precio',
                'verbose_name_plural': 'Historial de precios',
                'db_table': 'historial_precio_producto',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
