# Generated by Django 6.1.1 on 2026-09-27 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSeguridad',
            fields=[
                ('id_configuracion', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False, verbose_name='ID de configuración')),
                ('max_intentos_fallidos', models.PositiveSmallIntegerField(default=3, help_text='Intentos consecutivos con contraseña incorrecta antes de bloquear la cuenta.', verbose_name='Máximo de intentos fallidos')),
                ('minutos_bloqueo', models.PositiveIntegerField(default=10, help_text='Duración del bloqueo tras alcanzar el máximo de intentos fallidos.', verbose_name='Minutos de bloqueo')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_seguridad_actualizadas', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Configuración de Seguridad',
                'verbose_name_plural': 'Configuraciones de Seguridad',
                'db_table': 'configuracion_seguridad',
                'constraints': [models.CheckConstraint(condition=models.Q(('id_configuracion', 1)), name='configuracion_seguridad_singleton'), models.CheckConstraint(condition=models.Q(('max_intentos_fallidos__gte', 1), ('max_intentos_fallidos__lte', 20)), name='configuracion_seguridad_rango_intentos'), models.CheckConstraint(condition=models.Q(('minutos_bloqueo__gte', 1), ('minutos_bloqueo__lte', 1440)), name='configuracion_seguridad_rango_minutos')],
            },
        ),
    ]
