# Generated by Django 6.1.1 on 2026-09-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionseguridad',
            name='max_intentos_fallidos',
            field=models.PositiveSmallIntegerField(db_default=3, default=3, help_text='Intentos consecutivos con contraseña incorrecta antes de bloquear la cuenta.', verbose_name='Máximo de intentos fallidos'),
        ),
        migrations.AlterField(
            model_name='configuracionseguridad',
            name='minutos_bloqueo',
            field=models.PositiveIntegerField(db_default=10, default=10, help_text='Duración del bloqueo tras alcanzar el máximo de intentos fallidos.', verbose_name='Minutos de bloqueo'),
        ),
    ]
