# Generated by Django 6.1.1 on 2026-09-27 23:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_alter_configuracionseguridad_max_intentos_fallidos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionseguridad',
            name='max_intentos_token',
            field=models.PositiveSmallIntegerField(db_default=5, default=5, help_text='Confirmaciones fallidas con un mismo enlace antes de invalidarlo (CU2).', verbose_name='Máximo de intentos por token'),
        ),
        migrations.AddField(
            model_name='configuracionseguridad',
            name='max_solicitudes_por_hora',
            field=models.PositiveSmallIntegerField(db_default=3, default=3, help_text='Enlaces de recuperación que una misma cuenta puede pedir por hora (CU2).', verbose_name='Máximo de solicitudes por hora'),
        ),
        migrations.AddField(
            model_name='configuracionseguridad',
            name='minutos_expiracion_token',
            field=models.PositiveSmallIntegerField(db_default=15, default=15, help_text='Ventana de validez del enlace de recuperación de contraseña (CU2).', verbose_name='Minutos de expiración del token'),
        ),
        migrations.AddConstraint(
            model_name='configuracionseguridad',
            constraint=models.CheckConstraint(condition=models.Q(('minutos_expiracion_token__gte', 1), ('minutos_expiracion_token__lte', 1440)), name='configuracion_seguridad_rango_expiracion_token'),
        ),
        migrations.AddConstraint(
            model_name='configuracionseguridad',
            constraint=models.CheckConstraint(condition=models.Q(('max_intentos_token__gte', 1), ('max_intentos_token__lte', 20)), name='configuracion_seguridad_rango_intentos_token'),
        ),
        migrations.AddConstraint(
            model_name='configuracionseguridad',
            constraint=models.CheckConstraint(condition=models.Q(('max_solicitudes_por_hora__gte', 1), ('max_solicitudes_por_hora__lte', 20)), name='configuracion_seguridad_rango_solicitudes_hora'),
        ),
    ]
