-- =========================================================
-- BASE DE DATOS - SISTEMA DE INFORMACIÓN WEB
-- PANADERÍA SANTIAGO
-- PostgreSQL 14+
-- Versión final con correcciones de la docente
-- =========================================================
--
-- SINTAXIS DEL DOCUMENTO
--   Los comentarios que empiezan por `-- NUEVA` o `-- MODIFICADA` señalan
--   tablas y columnas que se agregaron o cambiaron al implementar los casos de
--   uso. Sirven para que la revisión distinga de un vistazo lo que es diseño
--   original de lo que agregado el equipo durante el desarrollo.
--
-- NOTA SOBRE LAS LLAVES PRIMARIAS
--   Las PK de las tablas del módulo de Usuarios y Seguridad usan
--   `GENERATED BY DEFAULT AS IDENTITY`. Es lo que realmente genera Django y lo
--   que evita el error "duplicate key value violates unique constraint" al
--   insertar sin especificar el id.
--
-- NOTA SOBRE LAS LLAVES FORÁNEAS
--   Todas las FK van `DEFERRABLE INITIALLY DEFERRED`, que es lo que emite
--   Django. La diferencia importa: con `INITIALLY IMMEDIATE` la FK se valida en
--   cada sentencia y no se puede reordenar un INSERT que referencie una fila
--   que todavia no existe en la misma transaccion. Con DEFERRED, PostgreSQL
--   valida todas las FK al final, y por eso se pueden cargar tablas que se
--   referencian entre si en cualquier orden.
-- =========================================================


-- =========================================================
-- MÓDULO: USUARIOS Y SEGURIDAD
-- =========================================================

CREATE TABLE "rol" (
  "id_rol" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(50) UNIQUE NOT NULL,
  "descripcion" text
);

-- MODIFICADA (CU4): se agrega columna `modulo` varchar(30) NOT NULL con valor
-- por defecto 'usuarios_seguridad' para agrupar los permisos según los 5 paquetes
-- del backend (PACKAGE_CU_MAP.md) y estructurar la matriz de permisos.
CREATE TABLE "permiso" (
  "id_permiso" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(50) UNIQUE NOT NULL,
  "descripcion" text,
  "modulo" varchar(30) NOT NULL DEFAULT 'usuarios_seguridad'
);

-- ALINEADA (CU4):
-- Se resuelve la deriva documentada en CU3 alineando el DDL a la arquitectura estándar
-- de Django. La tabla utiliza una clave primaria subrogada `id` y una restricción
-- UNIQUE compuesta ("id_rol", "id_permiso"), garantizando exactamente la misma regla de
-- negocio ("un rol no repite el mismo permiso") sin forzar claves primarias compuestas
-- experimentales en el ORM.
CREATE TABLE "rol_permiso" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_rol" bigint NOT NULL,
  "id_permiso" bigint NOT NULL,
  CONSTRAINT "rol_permiso_unico" UNIQUE ("id_rol", "id_permiso")
);

-- MODIFICADA (CU1): se le agregan las 3 columnas de control de bloqueo por
-- intentos fallidos, mas `is_staff`, `is_superuser` y `last_login` que Django
-- exige en su clase base de usuario.
--   intentos_fallidos      contador de fallos consecutivos. El CHECK impide que
--                          sea negativo, aunque la logica nunca lo seria.
--   bloqueado_hasta        instante en que expira la ventana de bloqueo. NULL
--                          significa que la cuenta NO esta bloqueada, y es el
--                          unico estado que la logica consulta para decidir.
--   ultimo_intento_fallido cuando ocurrio el ultimo fallo. Permite detectar un
--                          ataque en curso aunque todavia no haya bloqueo.
-- MODIFICADA (CU2): `email` pasa de NULL a NOT NULL, porque es el canal por el
-- que sale el enlace de recuperacion. Sin correo, el CU2 no tiene a donde
-- escribir. La unicidad va sobre `Lower("email")` y no sobre la columna, para
-- que "Persona@mail.com" y "persona@mail.com" no sean dos cuentas distintas
-- (ver el indice unico mas abajo).
-- NOTA (CU3): `nombre_usuario` conserva su `UNIQUE` de columna, pero la
-- garantia real de que no haya dos cuentas que solo difieran en mayusculas la
-- da el indice `usuario_username_unico_ci` de mas abajo. Ver el comentario de
-- ese indice antes de concluir nada leyendo solo la definicion de la columna.
CREATE TABLE "usuario" (
  "id_usuario" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_rol" bigint,
  "nombre_usuario" varchar(50) UNIQUE NOT NULL,
  "hash_contrasena" varchar(255) NOT NULL,
  "nombre_completo" varchar(150) NOT NULL,
  "email" varchar(150) NOT NULL,
  "activo" boolean NOT NULL DEFAULT true,
  "is_staff" boolean NOT NULL DEFAULT false,
  "is_superuser" boolean NOT NULL DEFAULT false,
  "last_login" timestamp with time zone,
  "intentos_fallidos" smallint NOT NULL DEFAULT 0
    CONSTRAINT "usuario_intentos_fallidos_no_negativo" CHECK ("intentos_fallidos" >= 0),
  "bloqueado_hasta" timestamp with time zone,
  "ultimo_intento_fallido" timestamp with time zone
);

-- NUEVO (CU2) - Unicidad del correo sin distinguir mayusculas.
-- Un UNIQUE sobre la columna no alcanzaria: PostgreSQL compara "Persona@mail.com"
-- y "persona@mail.com" como dos valores distintos, asi que las dos cuentas
-- coexistirian y la recuperacion de contrasena quedaria ambigua.
-- El nombre lleva el sufijo "_ci" (case insensitive) para que quede claro al
-- leer el esquema que la comparacion no distingue mayusculas.
CREATE UNIQUE INDEX "usuario_email_unico_ci" ON "usuario" (Lower("email"));

-- NUEVO (CU3) - Unicidad del nombre de usuario sin distinguir mayusculas.
--
-- Por que hace falta si arriba ya dice UNIQUE: porque el UNIQUE de columna en
-- PostgreSQL significa "unico y DISTINTO DE MAYUSCULAS". Con solo eso, "Admin"
-- y "admin" coexistian como dos cuentas validas, y como el login resuelve por
-- coincidencia exacta (`nombre_usuario = <lo que se escribio>`), una de las dos
-- quedaba permanentemente inaccesible. El Administrador veia una cuenta
-- "creada correctamente" que nadie podia usar, sin ninguna pista de por que.
--
-- Por que conviven los dos indices y no se elimina el UNIQUE de la columna:
-- Django exige por contrato (auth.E003) que el campo USERNAME_FIELD de un
-- modelo de usuario sea unico. Quitarlo rompe el sistema de autenticacion
-- entero, y silenciar esa verificacion con SILENCED_SYSTEM_CHECKS seria
-- esconder un problema real en lugar de resolverlo. El UNIQUE de columna queda
-- como el indice que usa la busqueda del login; este es el que decide si dos
-- cuentas pueden llamarse igual.
CREATE UNIQUE INDEX "usuario_username_unico_ci"
  ON "usuario" (Lower("nombre_usuario"));

-- MODIFICADA (CU1):
--   id_usuario  dejo de ser NOT NULL y su FK paso a ON DELETE SET NULL. Un
--               intento de acceso fallido ocurre justamente cuando NADIE esta
--               autenticado, asi que la bitacora debe poder registrarlo sin
--               usuario. Con ON DELETE SET NULL, borrar un usuario conserva su
--               historial de auditoria en vez de destruirlo.
--   accion      ahora esta controlada por el enum AccionBitacora del codigo
--               Python, para que una errata falle al escribirse y no cree en
--               silencio una categoria que ningun reporte agrupa.
-- NUEVAS (CU1):
--   nombre_usuario_intento  nombre digitado en un intento fallido, para poder
--                           correlacionar sin tener usuario autenticado.
--   agente_usuario          User-Agent del navegador. Junto con la IP
--                           distingue a una persona de un bot automatico.
-- MODIFICADA (CU3): `accion` sigue siendo `varchar(50)` —NO es un enum de
-- PostgreSQL ni una tabla de lookup— y su lista de valores admitidos crece en
-- el codigo Python (`AccionBitacora`). Por eso la migracion 0006 no altera ni
-- un byte de los registros que ya existen: agrega cuatro claves.
--     ALTA_USUARIO              alta de una cuenta
--     EDICION_USUARIO           modificacion de datos de una cuenta
--     CAMBIAR_ESTADO_USUARIO    activacion o inactivacion
--     RESTABLECER_CONTRASENA    reset administrativo de clave
-- `DESBLOQUEO_CUENTA`, que CU3 tambien usa al desbloquear una cuenta, ya
-- existia desde CU1 y se reutiliza tal cual. Partirla en dos habria dividido un
-- mismo hecho en dos filas de reporte.
CREATE TABLE "bitacora" (
  "id_bitacora" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" bigint,
  "nombre_usuario_intento" varchar(50),
  "agente_usuario" varchar(255),
  "accion" varchar(50) NOT NULL,
  "tabla_afectada" varchar(50),
  "descripcion" text,
  "fecha_hora" timestamp NOT NULL DEFAULT (now())
);

-- NUEVA (CU1) - Politica de bloqueo por intentos fallidos.
-- Fila unica: la clave primaria fija en 1, reforzada con un CHECK que impide
-- que exista una segunda fila. El umbral NO vive en settings.py precisely para
-- que el Administrador pueda cambiarlo sin desplegar.
-- Los dos CHECK de rango tambien evitan el error tonto de guardar 0 intentos
-- (dejaria la cuenta bloqueada siempre) o 0 minutos (bloqueo instantaneo).
-- MODIFICADA (CU2): se agregan los 3 parametros de la recuperacion de
-- contrasena, con el mismo criterio que los dos de CU1: el umbral lo decide el
-- Administrador desde el panel, no el equipo con un redeploy. Por eso viven en
-- la base y no en settings.py.
--   minutos_expiracion_token  vigencia del enlace de recuperacion.
--   max_intentos_token        cuantas confirmaciones admite un mismo enlace antes
--                             de quemarlo. Frena a quien robo un enlace y prueba
--                             contrasenas al azar.
--   max_solicitudes_por_hora   cuantos enlaces puede pedir una misma cuenta por
--                             hora. Protege el buzon del usuario.
CREATE TABLE "configuracion_seguridad" (
  "id_configuracion" smallint NOT NULL DEFAULT 1
    CONSTRAINT "configuracion_seguridad_singleton" CHECK ("id_configuracion" = 1),
  "max_intentos_fallidos" smallint NOT NULL DEFAULT 3
    CONSTRAINT "configuracion_seguridad_rango_intentos"
      CHECK ("max_intentos_fallidos" BETWEEN 1 AND 20),
  "minutos_bloqueo" integer NOT NULL DEFAULT 10
    CONSTRAINT "configuracion_seguridad_rango_minutos"
      CHECK ("minutos_bloqueo" BETWEEN 1 AND 1440),
  "actualizado_en" timestamp with time zone NOT NULL DEFAULT (now()),
  "actualizado_por_id" bigint,
  "minutos_expiracion_token" smallint NOT NULL DEFAULT 15
    CONSTRAINT "configuracion_seguridad_rango_expiracion_token"
      CHECK ("minutos_expiracion_token" BETWEEN 1 AND 1440),
  "max_intentos_token" smallint NOT NULL DEFAULT 5
    CONSTRAINT "configuracion_seguridad_rango_intentos_token"
      CHECK ("max_intentos_token" BETWEEN 1 AND 20),
  "max_solicitudes_por_hora" smallint NOT NULL DEFAULT 3
    CONSTRAINT "configuracion_seguridad_rango_solicitudes_hora"
      CHECK ("max_solicitudes_por_hora" BETWEEN 1 AND 20)
);
-- Nota: Django agrega ademas un CHECK ">= 0" por cada campo declarado como
-- PositiveSmallIntegerField. Son redundantes con los CHECK con nombre de arriba
-- y no se reproducen aqui para no ensuciar el DDL.

-- NUEVAS (CU1) - Lista negra de tokens JWT.
-- Las crea la app `rest_framework_simplejwt.token_blacklist` de Django. Se
-- declaran aqui para que el modelo fisico este completo. Sin estas dos tablas
-- el logout NO revocaria nada: el refresh token seguiria valido hasta cumplir
-- sus 7 dias, y la rotacion de tokens dejaria inservible al propio usuario.
CREATE TABLE "token_blacklist_outstandingtoken" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "token" text NOT NULL,
  "created_at" timestamp with time zone NOT NULL,
  "user" bigint NOT NULL,
  "jti" varchar(255) NOT NULL
);

CREATE TABLE "token_blacklist_blacklistedtoken" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "token" text NOT NULL,
  "created_at" timestamp with time zone NOT NULL,
  "expires_at" timestamp with time zone NOT NULL
);


-- =========================================================
-- MÓDULO: RECUPERACIÓN DE CONTRASEÑA (CU2)
-- =========================================================

-- NUEVA (CU2) - Enlaces de recuperacion de contrasena.
--
-- LA REGLA MAS IMPORTANTE DE ESTA TABLA: aqui NO se guarda el token. Se guarda
-- `token_hash`, que es el SHA-256 del token de 20 caracteres. El token en claro
-- sale unicamente por correo y existe en la RAM del proceso el instante en que
-- se genera. Si alguien lee esta tabla (un dump, un backup, una consulta del
-- Administrador) no tiene nada que clicksar.
--
-- El hash SHA-256 alcanza porque el token tiene ~100 bits de entropia: no hay
-- diccionario que atacar, asi que no hacen falta ni salt ni un algoritmo lento
-- tipo bcrypt. Con un codigo de 6 digitos el hash no habria servido de nada,
-- porque las 10^6 combinaciones se enumeran en un rato.
--
--   token_hash     SHA-256 hexadecimal (64 caracteres). UNIQUE: es por este
--                  valor por donde se busca, nunca por el token en claro.
--   email_destino   copia del correo en el momento de pedir el enlace. Si el
--                  usuario cambia su correo a mitad de camino, el enlace sigue
--                  siendo auditable aunque ya no apunte a la casilla actual.
--   creado_en       emision del enlace.
--   expira_en       vence por tiempo. El CHECK impide que se cargue una fila
--                  con la expiracion antes del alta.
--   usado_en        se pone cuando el enlace se consume con exito. Un enlace es
--                  de un SOLO uso.
--   invalidado_en   se pone cuando el enlace muere sin usarse: porque el usuario
--                  pidió otro, porque se agotaron los intentos, o por la purga
--                  de vencidos. NULL = el enlace sigue vivo.
--   intentos        confirmaciones ya consumidas contra este enlace. El tope lo
--                  fija `configuracion_seguridad.max_intentos_token`.
--   ip_origen       hasta 45 caracteres: cabe la IPv6 larga con su prefijo.
--   agente_usuario  User-Agent del navegador, truncado a 255.
--
-- `usado_en` y `invalidado_en` son los dos "muertes" posibles de un enlace, y
-- se guardan por separado a proposito: el informe de CU26 necesita distinguir
-- "el usuario completo el proceso" de "el enlace murio solo".
CREATE TABLE "token_recuperacion" (
  "id_token" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "token_hash" varchar(64) NOT NULL UNIQUE,
  "email_destino" varchar(150) NOT NULL,
  "creado_en" timestamp with time zone NOT NULL DEFAULT (now()),
  "expira_en" timestamp with time zone NOT NULL,
  "usado_en" timestamp with time zone,
  "invalidado_en" timestamp with time zone,
  "intentos" smallint NOT NULL DEFAULT 0
    CONSTRAINT "token_recuperacion_intentos_no_negativos" CHECK ("intentos" >= 0),
  "ip_origen" varchar(45),
  "agente_usuario" varchar(255),
  "usuario_id" bigint NOT NULL,
  CONSTRAINT "token_recuperacion_expiracion_positiva"
    CHECK ("expira_en" > "creado_en"),
  CONSTRAINT "token_recuperacion_uso_coherente"
    CHECK ("usado_en" IS NULL OR "usado_en" >= "creado_en")
);

-- Indice compuesto para la consulta de la cuota por hora, que cuenta los
-- enlaces que el usuario emitio en la ultima hora. El orden descendente en
-- `creado_en` hace que PostgreSQL pueda recorrer el indice desde el final, que
-- es justo la parte que interesa.
CREATE INDEX "token_recuperacion_usuario_idx"
  ON "token_recuperacion" ("usuario_id", "creado_en" DESC);

-- La FK va con ON DELETE CASCADE a proposito: si se borra la cuenta, sus
-- enlaces deben morir con ella. Un token huerfano apuntando a un usuario
-- inexistente permitiria reiniciar el reloj de un enlace viejo. La cascada se
-- puso con la migracion `recuperacion.0002_fk_token_recuperacion_cascade`,
-- porque Django NO la habia aplicado por su cuenta (para su editor de esquemas
-- `on_delete` no es un parametro de base de datos y la emite como no-op).
ALTER TABLE "token_recuperacion"
  ADD CONSTRAINT "token_recuperacion_usuario_id_fk"
  FOREIGN KEY ("usuario_id") REFERENCES "usuario"("id_usuario")
  ON DELETE CASCADE
  DEFERRABLE INITIALLY DEFERRED;


-- =========================================================
-- MÓDULO: PRODUCTOS
-- =========================================================

CREATE TABLE "categoria_producto" (
  "id_categoria" bigint PRIMARY KEY,
  "nombre" varchar(50) NOT NULL,
  "descripcion" text
);

CREATE TABLE "producto" (
  "id_producto" bigint PRIMARY KEY,
  "id_categoria" bigint,
  "nombre" varchar(100) NOT NULL,
  "descripcion" text,
  "costo_produccion" decimal(10,2) NOT NULL DEFAULT 0,
  "porcentaje_ganancia" decimal(5,2) NOT NULL DEFAULT 0,
  "precio_sugerido" decimal(10,2) NOT NULL DEFAULT 0,
  "precio_venta" decimal(10,2) NOT NULL DEFAULT 0,
  "fecha_registro" timestamp NOT NULL DEFAULT (now()),
  "activo" boolean NOT NULL DEFAULT true
);

CREATE TABLE "producto_materia_prima" (
  "id_producto" bigint NOT NULL,
  "id_materia_prima" bigint NOT NULL,
  "cantidad_requerida" decimal(10,3) NOT NULL,
  "unidad_medida" varchar(20) NOT NULL,
  PRIMARY KEY ("id_producto", "id_materia_prima")
);

CREATE TABLE "historial_precio_producto" (
  "id_historial" bigint PRIMARY KEY,
  "id_producto" bigint NOT NULL,
  "precio" decimal(10,2) NOT NULL,
  "fecha_inicio" timestamp NOT NULL DEFAULT (now())
);


-- =========================================================
-- MÓDULO: PRODUCCIÓN Y COMERCIALIZACIÓN
-- =========================================================

CREATE TABLE "cliente" (
  "id_cliente" bigint PRIMARY KEY,
  "nombre" varchar(150) NOT NULL,
  "telefono" varchar(20),
  "direccion" varchar(200)
);

CREATE TABLE "pedido" (
  "id_pedido" bigint PRIMARY KEY,
  "id_cliente" bigint NOT NULL,
  "id_usuario" bigint NOT NULL,
  "fecha_registro" timestamp NOT NULL DEFAULT (now()),
  "fecha_entrega" timestamp,
  "estado" varchar(20) NOT NULL DEFAULT 'pendiente',
  "metodo_pago" varchar(20),
  "total" decimal(10,2) NOT NULL DEFAULT 0
);

CREATE TABLE "detalle_pedido" (
  "id_detalle_pedido" bigint PRIMARY KEY,
  "id_pedido" bigint NOT NULL,
  "id_producto" bigint NOT NULL,
  "cantidad" int NOT NULL,
  "precio_unitario" decimal(10,2) NOT NULL,
  "subtotal" decimal(10,2) NOT NULL
);

CREATE TABLE "venta" (
  "id_venta" bigint PRIMARY KEY,
  "id_pedido" bigint UNIQUE,
  "id_usuario" bigint NOT NULL,
  "numero_comprobante" bigint UNIQUE NOT NULL,
  "fecha_hora" timestamp NOT NULL DEFAULT (now()),
  "metodo_pago" varchar(20) NOT NULL,
  "id_transaccion_stripe" varchar(100),
  "total" decimal(10,2) NOT NULL DEFAULT 0
);

CREATE TABLE "detalle_venta" (
  "id_detalle_venta" bigint PRIMARY KEY,
  "id_venta" bigint NOT NULL,
  "id_producto" bigint NOT NULL,
  "cantidad" int NOT NULL,
  "precio_unitario" decimal(10,2) NOT NULL,
  "subtotal" decimal(10,2) NOT NULL
);

CREATE TABLE "produccion" (
  "id_produccion" bigint PRIMARY KEY,
  "id_usuario" bigint NOT NULL,
  "fecha" date NOT NULL,
  "jornada" varchar(20)
);

CREATE TABLE "detalle_produccion" (
  "id_detalle_produccion" bigint PRIMARY KEY,
  "id_produccion" bigint NOT NULL,
  "id_producto" bigint NOT NULL,
  "cantidad_producida" int NOT NULL,
  "costo_unitario" decimal(10,2) NOT NULL
);

CREATE TABLE "nota_perdida_producto" (
  "id_nota_perdida" bigint PRIMARY KEY,
  "id_detalle_produccion" bigint NOT NULL,
  "id_usuario" bigint NOT NULL,
  "cantidad" int NOT NULL,
  "costo_unitario" decimal(10,2) NOT NULL,
  "fecha_salida" timestamp NOT NULL DEFAULT (now())
);


-- =========================================================
-- MÓDULO: INVENTARIO DE MATERIA PRIMA
-- =========================================================

CREATE TABLE "materia_prima" (
  "id_materia_prima" bigint PRIMARY KEY,
  "nombre" varchar(100) NOT NULL,
  "unidad_medida" varchar(20) NOT NULL,
  "stock_minimo" decimal(10,3) NOT NULL DEFAULT 0,
  "fecha_registro" timestamp NOT NULL DEFAULT (now()),
  "activo" boolean NOT NULL DEFAULT true
);

CREATE TABLE "historial_precio_materia_prima" (
  "id_historial" bigint PRIMARY KEY,
  "id_materia_prima" bigint NOT NULL,
  "precio" decimal(10,2) NOT NULL,
  "fecha_inicio" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "inventario_materia_prima" (
  "id_inventario" bigint PRIMARY KEY,
  "id_materia_prima" bigint UNIQUE NOT NULL,
  "stock_actual" decimal(10,3) NOT NULL DEFAULT 0
);

CREATE TABLE "movimiento_materia_prima" (
  "id_movimiento" bigint PRIMARY KEY,
  "id_inventario" bigint NOT NULL,
  "id_compra" bigint,
  "id_produccion" bigint,
  "fecha_hora" timestamp NOT NULL DEFAULT (now()),
  "tipo" varchar(10) NOT NULL,
  "cantidad" decimal(10,3) NOT NULL
);


-- =========================================================
-- MÓDULO: INVENTARIO DE PRODUCTOS TERMINADOS
-- =========================================================

CREATE TABLE "inventario_producto_terminado" (
  "id_inventario" bigint PRIMARY KEY,
  "id_producto" bigint UNIQUE NOT NULL,
  "stock_actual" int NOT NULL DEFAULT 0
);

CREATE TABLE "movimiento_producto_terminado" (
  "id_movimiento" bigint PRIMARY KEY,
  "id_inventario" bigint NOT NULL,
  "id_produccion" bigint,
  "id_venta" bigint,
  "id_pedido" bigint,
  "id_nota_perdida" bigint,
  "fecha_hora" timestamp NOT NULL DEFAULT (now()),
  "tipo" varchar(10) NOT NULL,
  "cantidad" int NOT NULL
);


-- =========================================================
-- MÓDULO: COMPRAS, PROVEEDORES Y GASTOS
-- =========================================================

CREATE TABLE "proveedor" (
  "id_proveedor" bigint PRIMARY KEY,
  "nombre" varchar(150) NOT NULL,
  "telefono" varchar(20),
  "direccion" varchar(200),
  "fecha_registro" timestamp NOT NULL DEFAULT (now()),
  "activo" boolean NOT NULL DEFAULT true
);

CREATE TABLE "compra" (
  "id_compra" bigint PRIMARY KEY,
  "id_proveedor" bigint NOT NULL,
  "id_usuario" bigint NOT NULL,
  "fecha_hora" timestamp NOT NULL DEFAULT (now()),
  "total" decimal(10,2) NOT NULL DEFAULT 0
);

CREATE TABLE "detalle_compra" (
  "id_detalle_compra" bigint PRIMARY KEY,
  "id_compra" bigint NOT NULL,
  "id_materia_prima" bigint NOT NULL,
  "cantidad" decimal(10,3) NOT NULL,
  "precio_unitario" decimal(10,2) NOT NULL,
  "subtotal" decimal(10,2) NOT NULL
);

CREATE TABLE "movimiento_economico" (
  "id_movimiento" bigint PRIMARY KEY,
  "id_usuario" bigint NOT NULL,
  "tipo" varchar(20) NOT NULL,
  "concepto" varchar(100) NOT NULL,
  "descripcion" text,
  "monto" decimal(10,2) NOT NULL,
  "fecha_hora" timestamp NOT NULL DEFAULT (now())
);


-- =========================================================
-- LLAVES FORÁNEAS - USUARIOS Y SEGURIDAD
-- =========================================================

ALTER TABLE "rol_permiso" ADD FOREIGN KEY ("id_rol") REFERENCES
"rol" ("id_rol") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "rol_permiso" ADD FOREIGN KEY ("id_permiso") REFERENCES
"permiso" ("id_permiso") DEFERRABLE INITIALLY DEFERRED;

-- CU4: ON DELETE SET NULL. Dejar un rol sin asignar o borrar un rol no debe
-- disparar violación de clave foránea ni eliminar la cuenta del usuario.
ALTER TABLE "usuario" ADD FOREIGN KEY ("id_rol") REFERENCES
"rol" ("id_rol") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

-- CU1: ON DELETE SET NULL. Borrar un usuario pone en NULL el id_usuario de sus
-- registros de auditoria en lugar de impedirse o de destruirlos. Sin este
-- ON DELETE, un DELETE directo por SQL (pgAdmin, un script de la docente) falla
-- con "viola la llave foranea" aunque la columna ya admita NULL.
ALTER TABLE "bitacora" ADD FOREIGN KEY ("id_usuario") REFERENCES
"usuario" ("id_usuario") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

-- CU1: la bitacora de la politica de seguridad guarda quien la modifico.
ALTER TABLE "configuracion_seguridad" ADD FOREIGN KEY ("actualizado_por_id") REFERENCES
"usuario" ("id_usuario") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

-- CU1: la lista negra de tokens apunta al usuario emisor del refresh token.
ALTER TABLE "token_blacklist_outstandingtoken" ADD FOREIGN KEY ("user") REFERENCES
"usuario" ("id_usuario") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;


-- =========================================================
-- LLAVES FORÁNEAS - PRODUCTOS
-- =========================================================

ALTER TABLE "producto" ADD FOREIGN KEY ("id_categoria") REFERENCES
"categoria_producto" ("id_categoria") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "producto_materia_prima" ADD FOREIGN KEY ("id_producto") REFERENCES
"producto" ("id_producto") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "producto_materia_prima" ADD FOREIGN KEY ("id_materia_prima") REFERENCES
"materia_prima" ("id_materia_prima") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "historial_precio_producto" ADD FOREIGN KEY ("id_producto") REFERENCES
"producto" ("id_producto") DEFERRABLE INITIALLY DEFERRED;


-- =========================================================
-- LLAVES FORÁNEAS - PEDIDOS Y VENTAS
-- =========================================================

ALTER TABLE "pedido" ADD FOREIGN KEY ("id_cliente") REFERENCES
"cliente" ("id_cliente") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "pedido" ADD FOREIGN KEY ("id_usuario") REFERENCES
"usuario" ("id_usuario") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "detalle_pedido" ADD FOREIGN KEY ("id_pedido") REFERENCES
"pedido" ("id_pedido") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "detalle_pedido" ADD FOREIGN KEY ("id_producto") REFERENCES
"producto" ("id_producto") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "venta" ADD FOREIGN KEY ("id_pedido") REFERENCES
"pedido" ("id_pedido") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "venta" ADD FOREIGN KEY ("id_usuario") REFERENCES
"usuario" ("id_usuario") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "detalle_venta" ADD FOREIGN KEY ("id_venta") REFERENCES
"venta" ("id_venta") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "detalle_venta" ADD FOREIGN KEY ("id_producto") REFERENCES
"producto" ("id_producto") DEFERRABLE INITIALLY DEFERRED;


-- =========================================================
-- LLAVES FORÁNEAS - PRODUCCIÓN
-- =========================================================

ALTER TABLE "produccion" ADD FOREIGN KEY ("id_usuario") REFERENCES
"usuario" ("id_usuario") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "detalle_produccion" ADD FOREIGN KEY ("id_produccion") REFERENCES
"produccion" ("id_produccion") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "detalle_produccion" ADD FOREIGN KEY ("id_producto") REFERENCES
"producto" ("id_producto") DEFERRABLE INITIALLY DEFERRED;


-- =========================================================
-- LLAVES FORÁNEAS - NOTA DE PÉRDIDA DE PRODUCTO
-- =========================================================

ALTER TABLE "nota_perdida_producto" ADD FOREIGN KEY ("id_detalle_produccion")
REFERENCES "detalle_produccion" ("id_detalle_produccion") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "nota_perdida_producto" ADD FOREIGN KEY ("id_usuario") REFERENCES
"usuario" ("id_usuario") DEFERRABLE INITIALLY DEFERRED;


-- =========================================================
-- LLAVES FORÁNEAS - INVENTARIO MATERIA PRIMA
-- =========================================================

ALTER TABLE "historial_precio_materia_prima" ADD FOREIGN KEY ("id_materia_prima")
REFERENCES "materia_prima" ("id_materia_prima") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "inventario_materia_prima" ADD FOREIGN KEY ("id_materia_prima")
REFERENCES "materia_prima" ("id_materia_prima") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "movimiento_materia_prima" ADD FOREIGN KEY ("id_inventario")
REFERENCES "inventario_materia_prima" ("id_inventario") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "movimiento_materia_prima" ADD FOREIGN KEY ("id_compra")
REFERENCES "compra" ("id_compra") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "movimiento_materia_prima" ADD FOREIGN KEY ("id_produccion")
REFERENCES "produccion" ("id_produccion") DEFERRABLE INITIALLY DEFERRED;


-- =========================================================
-- LLAVES FORÁNEAS - INVENTARIO PRODUCTO TERMINADO
-- =========================================================

ALTER TABLE "inventario_producto_terminado" ADD FOREIGN KEY ("id_producto")
REFERENCES "producto" ("id_producto") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "movimiento_producto_terminado" ADD FOREIGN KEY ("id_inventario")
REFERENCES "inventario_producto_terminado" ("id_inventario") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "movimiento_producto_terminado" ADD FOREIGN KEY ("id_produccion")
REFERENCES "produccion" ("id_produccion") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "movimiento_producto_terminado" ADD FOREIGN KEY ("id_venta")
REFERENCES "venta" ("id_venta") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "movimiento_producto_terminado" ADD FOREIGN KEY ("id_pedido")
REFERENCES "pedido" ("id_pedido") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "movimiento_producto_terminado" ADD FOREIGN KEY ("id_nota_perdida")
REFERENCES "nota_perdida_producto" ("id_nota_perdida") DEFERRABLE INITIALLY DEFERRED;


-- =========================================================
-- LLAVES FORÁNEAS - COMPRAS, PROVEEDORES Y GASTOS
-- =========================================================

ALTER TABLE "compra" ADD FOREIGN KEY ("id_proveedor") REFERENCES
"proveedor" ("id_proveedor") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "compra" ADD FOREIGN KEY ("id_usuario") REFERENCES
"usuario" ("id_usuario") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "detalle_compra" ADD FOREIGN KEY ("id_compra") REFERENCES
"compra" ("id_compra") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "detalle_compra" ADD FOREIGN KEY ("id_materia_prima") REFERENCES
"materia_prima" ("id_materia_prima") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "movimiento_economico" ADD FOREIGN KEY ("id_usuario") REFERENCES
"usuario" ("id_usuario") DEFERRABLE INITIALLY DEFERRED;
